# Generated by Django 4.2.7 on 2023-11-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('validity_period', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricity_plan',
            name='price',
        ),
        migrations.AlterField(
            model_name='electricity_plan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricity_plan',
            name='pricing_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pricing_detail'),
        ),
    ]
