# Generated by Django 4.2.7 on 2023-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pricing_detail_remove_electricity_plan_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity_plan',
            name='pricing_detail',
        ),
        migrations.AddField(
            model_name='electricity_plan',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='electricity_plan',
            name='electricity_plan_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='electricity_plan',
            name='validity_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Pricing_Detail',
        ),
    ]
