# Generated by Django 4.2.7 on 2023-11-17 00:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_electricity_plan_pricing_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity_plan',
            name='electricity_plan_price',
        ),
        migrations.RemoveField(
            model_name='electricity_plan',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='electricity_pin',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 0, 24, 20, 962205)),
        ),
        migrations.AddField(
            model_name='electricity_pin',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity_pin',
            name='number_of_units',
            field=models.CharField(blank=True, max_length=365, null=True),
        ),
        migrations.AddField(
            model_name='electricity_plan',
            name='number_of_units',
            field=models.CharField(blank=True, max_length=365, null=True),
        ),
        migrations.AddField(
            model_name='electricity_plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricity_pin',
            name='pin',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('meter_id', models.CharField(max_length=20)),
                ('electricity_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electricity_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electricity_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_validity_days', models.IntegerField()),
                ('percentage_consumed', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
