# Generated by Django 4.2.7 on 2023-11-17 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_electricity_plan_electricity_plan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_pin',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 7, 48, 51, 99020)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_expiry_date',
            field=models.CharField(max_length=10),
        ),
    ]
