# Generated by Django 4.2.7 on 2023-11-18 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_electricity_pin_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_pin',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 0, 48, 59, 138604)),
        ),
    ]
