# Generated by Django 4.2.7 on 2023-11-18 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_electricity_pin_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionreader',
            name='remaining_validity_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricity_pin',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 0, 53, 31, 747287)),
        ),
    ]
